#!/bin/bash
# exported vars
export BLIPP_SRC_DIR
export BLIPP_BIN_DIR
# Get current source directory
origdir=$(pwd)
reldir=$(dirname $BASH_SOURCE)
BLIPP_SRC_DIR=$(cd ${reldir} >/dev/null ; pwd)
BLIPP_BIN_DIR=${BLIPP_SRC_DIR}/bin
cd ${origdir}
# Add to PYTHONPATH if not already present
r=$(echo $PYTHONPATH | grep -c ${BLIPP_SRC_DIR})
if [ $r -eq 0 ]; then
    export PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}${BLIPP_SRC_DIR}
fi
# Add to PATH if not already present
r=$(echo $PATH | grep -c ${BLIPP_BIN_DIR})
if [ $r -eq 0 ]; then
    export PATH=${PATH}:${BLIPP_BIN_DIR}
fi
